models:  
  openrouter-gpt-oss:
    model_url: "https://openrouter.ai/api/v1/chat/completions"
    model_name: "openai/gpt-oss-120b"
    api_key: "${OPENROUTER_API_KEY}"
    description: "OpenRouter aggregated openai gpt-oss 120B model"
    compliance_level: "External"
    # extra_headers:
    #   HTTP-Referer: "${OPENROUTER_SITE_URL}"
    #   X-Title: "${OPENROUTER_SITE_NAME}"


  gpt-4.1-nano:
    model_url: "https://api.openai.com/v1/chat/completions"
    model_name: "gpt-4.1-nano"
    api_key: "${OPENAI_API_KEY}"
    compliance_level: "External"
  cerebras-gpt-oss-120b:
    model_url: "https://api.cerebras.ai/v1"
    model_name: "gpt-oss-120b"
    api_key: "${CEREBRAS_API_KEY}"
    compliance_level: "External"
  groq-gpt-oss-120b:
    model_url: "https://api.groq.com/openai/v1"
    model_name: "openai/gpt-oss-120b"
    api_key: "${GROQ_API_KEY}"
    compliance_level: "External"
